apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-app
  labels:
    app: hello
  namespace: dev
spec:
  replicas: 3
  revisionHistoryLimit: 30
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: go-hello-app
        image: 249784/go-hello-app:slim1.0.0 
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /readiness
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080


